version: "3.9"
services:
  postgres-db:
    image: postgres
    container_name: earthquake-monitoring-postgres-db
    ports:
      - '5432:5432'
    volumes: 
      - ../databases/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: YOUR_POSTGRESDB_PASSWORD
  redis-db:
    image: earthquake-monitoring-redis-db
    container_name: earthquake-monitoring-redis-db
    build: ./dockerimages/redis
    ports:
      - '6379:6379'
    depends_on:
      - postgres-db