version: "3.9"
services:
  postgres-db:
    image: postgres
    container_name: earthquake-monitoring-postgres-db
    ports:
      - '5432:5432'
    volumes: 
      - ../databases/postgres:/var/lib/postgresql/data
    environment:
      #! you HAVE TO update the following ENV variable
      POSTGRES_PASSWORD: YOUR_POSTGRESDB_PASSWORD
  redis-db:
    image: earthquake-monitoring-redis-db
    container_name: earthquake-monitoring-redis-db
    build: ./dockerimages/redis
    ports:
      - '6379:6379'
    depends_on:
      - postgres-db
  cronjob:
    build: 
      dockerfile: cronjob/Dockerfile
      context: ../
    environment: #! you HAVE TO update, all of ENV variables
      POSTGRES_DATABASE_URL: "postgresql://postgres:YOUR_POSTGRESDB_PASSWORD@postgres-db:5432"
      NEXT_JS_API_ROUTE: "http://next:3000/api/revalidate"
      NEXT_JS_API_KEY: "YOUR_API_REVALIDATE_KEY"
    depends_on:
      - postgres-db
  web:
    build:
      dockerfile: web/Dockerfile
      context: ../
    container_name: earthquake-monitoring-next
    ports:
      - "3000:3000"
    environment: #! you HAVE TO update, all of ENV variables
      POSTGRES_DATABASE_URL: "postgresql://postgres:YOUR_POSTGRESDB_PASSWORD@postgres-db:5432"
      REDIS_DATABASE_URL: "redis://redis-db:6379"
      API_REVALIDATE_KEY: "YOUR_API_REVALIDATE_KEY"
    depends_on:
      - cronjob
      - postgres-db
      - redis-db