name: Build Android

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

defaults:
  run:
    working-directory: mobile

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Installing PNPM
        run: npm install -g pnpm

      - name: Install app dependencies
        run: pnpm install

      - name: Generating prisma types
        run: pnpm run prisma-types

      - name: Adding android to capacitor
        run: npx cap add android 

      - name: Build application
        run: pnpm run android-build

      - name: Build apps apk
        run: cd android && bash ./gradlew assembleRelease --stacktrace

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: mobile/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.RELEASE_KEYSTORE }}
          alias: ${{ secrets.KEYSOTRE_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.github_token }}
          files: ${{ steps.sign_app.outputs.signedReleaseFile }}
          draft: true