name: Build Android

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

defaults:
  run:
    working-directory: mobile

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu'
            java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Installing PNPM
        run: npm install -g pnpm

      - name: Install app dependencies
        run: pnpm install

      - name: Generating prisma types
        run: pnpm run prisma-types

      - name: Adding android to capacitor
        run: npx cap add android 

      - name: Build application
        run: pnpm run android-build

      - name: Build apps apk
        run: cd android && bash ./gradlew assembleRelease --stacktrace

          
      - name: Upload APK to Release
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: android/app/build/outputs/apk/release/**.apk